title:             qige's blog
email:             qigeloveit@163.com
description:		"生命的意义, 就在于生活的过程"
author:            qige
baseurl:           "/"
url:               "https://qigeloveit.github.io"

# Social Profiles
github_username:   qigeloveit

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
