permalink:			/:year/:month/:day/:title.html
markdown:			kramdown

title:				qige
tagline:			'A Technology blog'
description:		'Technology blog of qige'
url:				https://github.com/qigeloveit/qigeloveit.github.io
baseurl:			/

plugins:
  - jekyll-gist

paginate:			5
version:			1.0.0

author:
  name:				'qige'
  url:       		https://github.com/qigeloveit/qigeloveit.github.io
